# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Pogo
site_url: https://nrwldev.github.io/pogo-migrate/
repo_name: pogo-migrate
repo_url: https://github.com/NRWLDev/pogo-migrate
nav:
  - index.md
  - why-pogo.md
  - usage.md
  - configuration.md
  - testing.md
  - thanks.md
theme:
  name: material
  favicon: favicon.svg
  icon:
    logo: fontawesome/solid/database
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:admin@nrwl.co
