---
version: '3'
services:
  pogo_postgres_unit:
    image: postgres:14-alpine
    container_name: pogo-postgres-test
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: unit
      POSTGRES_DB: unit
    networks:
      - pogo-unit


networks:
  pogo-unit:
