class TestReadSqlMigration:
    def test_no_apply_section(self): ...
    def test_no_rollback_section(self): ...
    def test_invalid_metadata(self): ...
    def test_apply_func_created(self): ...
    def test_rollback_func_created(self): ...


class TestMigration:
    def test_migrations_superset_tracked(self): ...
    def test_applied(self): ...
    def test_depends(self): ...
    def test_depends_ids(self): ...
    def test_is_sql(self): ...  # t/f
    def test_apply(self): ...
    def test_rollback(self): ...
    def test_load_sql(self): ...
    def test_load_python(self): ...
    def test_load_invalid_python(self): ...
    def test_doc(self): ...


class TestTopologicalSort:
    def test_migrations_sorted(self): ...
    def test_cyclic_error(self): ...
