name: Publish

on:
  push:
    tags:
    - 'v\d+\.\d+\.\d+.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.x"
    - name: Install dependencies and configure
      run: |
        python -m pip install --upgrade poetry invoke
        poetry config pypi-token.pypi ${{ secrets.PYPI_PUBLISH_TOKEN }}
    - name: Publish
      run: poetry publish --build
